# -*- coding: utf-8 -*-
"""Untitled52.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1txH4qRWIV6nM4Z5QY4OyERmiuNuWw4Z2
"""

# Optimized Data Engineering PoC (Olist + PaySim) – Memory‑safe, per‑group imputation, type optimisation
# Run in Google Colab

import pandas as pd
import numpy as np
import random
from google.colab import drive

"""# Task
Fix the `SyntaxError` in the cell with `cell_id: 6yOJ7rNLboD9` by replacing the non-standard hyphen in the comment `1. Memory‑safe random sampling (chunk‑based)` with a standard hyphen.

## Fix non-standard hyphen in comment

### Subtask:
Replace the non-standard hyphen '‑' (U+2011) with a standard hyphen '-' (U+002D) in the comment of the `random_sample_csv` function definition cell to resolve the `SyntaxError`.

## Summary:

### Data Analysis Key Findings
- A `SyntaxError` was identified in the cell with `cell_id: 6yOJ7rNLboD9`.
- The error was caused by the presence of a non-standard hyphen character (U+2011, `\u2011`) within a comment: `1. Memory‑safe random sampling (chunk‑based)`.
- The `SyntaxError` was resolved by replacing the non-standard hyphen with a standard hyphen (U+002D, `-`) in the comment.

### Insights or Next Steps
- **Insight:** The use of non-standard characters, even in code comments, can lead to unexpected syntax errors or parsing issues in certain programming environments.
- **Next Step:** To prevent similar issues, it's recommended to consistently use standard ASCII characters for code comments and string literals, particularly in shared or cross-platform codebases.
"""

# 1. Memory-safe random sampling (chunk-based)
# ------------------------------
def random_sample_csv(file_path, sample_size=100000, chunksize=10000, random_state=42):
    """
    Reads a large CSV and returns a random sample of ~sample_size rows.
    Iterates over chunks and samples proportionally without loading the whole file.
    """
    random.seed(random_state)
    np.random.seed(random_state)

    # Count total rows (excluding header)
    with open(file_path, 'r') as f:
        total_rows = sum(1 for _ in f) - 1

    frac = sample_size / total_rows if total_rows > sample_size else 1.0

    sampled_dfs = []
    for chunk in pd.read_csv(file_path, chunksize=chunksize):
        sampled_chunk = chunk.sample(frac=frac, random_state=random_state)
        sampled_dfs.append(sampled_chunk)

        current_size = sum(len(df) for df in sampled_dfs)
        if current_size >= sample_size * 1.1:
            break

    result = pd.concat(sampled_dfs, ignore_index=True)
    if len(result) > sample_size:
        result = result.sample(n=sample_size, random_state=random_state)
    return result

# 2. Per‑group outlier detection & imputation
# ------------------------------
def detect_outliers_iqr(series):
    """Return boolean mask where True indicates outlier."""
    Q1 = series.quantile(0.25)
    Q3 = series.quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    return (series < lower) | (series > upper)

def impute_numeric_column_per_group(df, col, group_col=None):
    """
    Impute missing values in a numeric column.
    - If outliers exist WITHIN EACH GROUP → use group median.
    - Else → use group mean.
    If group_col is None, applies globally.
    """
    if group_col is None or group_col not in df.columns:
        # Global imputation (fallback)
        non_null = df[col].dropna()
        if len(non_null) == 0:
            return df
        outliers_exist = detect_outliers_iqr(non_null).any()
        fill_value = non_null.median() if outliers_exist else non_null.mean()
        df[col].fillna(fill_value, inplace=True)
        return df

    # Per‑group imputation
    for group_val, group_data in df.groupby(group_col):
        mask = df[group_col] == group_val
        non_null = group_data[col].dropna()
        if len(non_null) == 0:
            continue
        outliers_exist = detect_outliers_iqr(non_null).any()
        fill_value = non_null.median() if outliers_exist else non_null.mean()
        df.loc[mask & df[col].isnull(), col] = fill_value
    return df

def impute_categorical_column(df, col):
    """Impute missing values with the mode (global)."""
    mode_val = df[col].mode()
    if not mode_val.empty:
        df[col].fillna(mode_val[0], inplace=True)
    return df

# 3. Memory optimisation (downcasting + categoricals)
# ------------------------------
def optimise_dtypes(df):
    """
    - Downcast int64 → int32 / float64 → float32 where safe.
    - Convert low‑cardinality object columns (unique < 50) to 'category'.
    """
    for col in df.columns:
        col_type = df[col].dtype

        if col_type == 'int64':
            df[col] = pd.to_numeric(df[col], downcast='integer')
        elif col_type == 'float64':
            df[col] = pd.to_numeric(df[col], downcast='float')
        elif col_type == 'object':
            if df[col].nunique() / len(df) < 0.5 and df[col].nunique() < 50:
                df[col] = df[col].astype('category')
    return df


# ------------------------------
# 4. Time‑series transformation (PaySim step)
# ------------------------------
def map_step_to_time_features(df, step_col='step'):
    """Map PaySim 'step' (hourly units) into time_of_day and day_of_week."""
    hour = df[step_col] % 24
    day_idx = (df[step_col] // 24) % 7  # 0 = Monday

    conditions = [
        (hour >= 5) & (hour < 12),
        (hour >= 12) & (hour < 17),
        (hour >= 17) & (hour < 21),
        (hour >= 21) | (hour < 5)
    ]
    choices = ['Morning', 'Afternoon', 'Evening', 'Night']
    df['time_of_day'] = np.select(conditions, choices, default='')

    days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    df['day_of_week'] = day_idx.map(lambda x: days[int(x)])
    return df

# 5. Main PoC pipeline (with Olist pre‑merge)
# ------------------------------
def run_poc(customers_path, orders_path, paysim_path, sample_size=100000):
    print("="*60)
    print("OPTIMIZED DATA ENGINEERING PoC (with pre‑merge & per‑group imputation)")
    print("="*60)

    # ---- 5.1 Load random samples from Olist customers and orders ----
    print("\n[1] Loading random samples from Olist customers & orders...")
    customers_sample = random_sample_csv(customers_path, sample_size=sample_size)
    orders_sample = random_sample_csv(orders_path, sample_size=sample_size)

    print(f"Customers sample shape: {customers_sample.shape}")
    print(f"Orders sample shape: {orders_sample.shape}")

    # ---- 5.2 Merge Olist customers + orders on 'customer_id' ----
    print("\n[2] Merging Olist customers & orders on 'customer_id'...")
    # Required columns:
    # - customers: customer_id, customer_unique_id
    # - orders: customer_id, order_purchase_timestamp
    olist_merged = pd.merge(
        customers_sample, orders_sample,
        on='customer_id', how='inner'
    )
    print(f"Shape after inner join (customers ↔ orders): {olist_merged.shape}")

    # Keep only needed columns for next merge with PaySim
    # We need customer_unique_id and order_purchase_timestamp
    olist_ready = olist_merged[['customer_unique_id', 'order_purchase_timestamp']].drop_duplicates()

    # ---- 5.3 Load PaySim sample ----
    print("\n[3] Loading PaySim sample...")
    paysim_sample = random_sample_csv(paysim_path, sample_size=sample_size)
    print(f"PaySim sample shape: {paysim_sample.shape}")

    # ---- 5.4 Merge Olist (customer_unique_id) with PaySim (nameOrig) ----
    print("\n[4] Merging Olist with PaySim (inner join on customer_unique_id ↔ nameOrig)...")
    merged = pd.merge(
        olist_ready, paysim_sample,
        left_on='customer_unique_id', right_on='nameOrig',
        how='inner'
    )
    print(f"Final merged shape: {merged.shape}")

    if merged.empty:
        print("   Warning: Merged DataFrame is empty. This might indicate no common IDs between Olist and PaySim samples.")
        print("   Skipping further processing steps as there is no data to process.")
        print("\n" + "="*60)
        print("PoC COMPLETED WITH EMPTY MERGED DATASET")
        print("="*60)
        return pd.DataFrame()

    # ---- 5.5 Time‑series transformation ----
    print("\n[5] Applying time-series transformations...")
    # Olist timestamp
    merged['order_purchase_timestamp'] = pd.to_datetime(merged['order_purchase_timestamp'])
    merged['order_hour'] = merged['order_purchase_timestamp'].dt.hour
    merged['order_dayofweek'] = merged['order_purchase_timestamp'].dt.dayofweek

    # PaySim step → time features
    if 'step' in merged.columns:
        merged = map_step_to_time_features(merged, step_col='step')
        print("   Added 'time_of_day' and 'day_of_week' from PaySim 'step'.")

    # ---- 5.6 Missing values before imputation ----
    print("\n[6] Missing values BEFORE imputation:")
    missing_before = merged.isnull().sum()
    print(missing_before[missing_before > 0] if (missing_before > 0).any() else "   No missing values found.")

    # ---- 5.7 Per‑group imputation ----
    print("\n[7] Applying PER‑GROUP imputation (grouped by PaySim 'type' where available)...")
    # Identify numeric columns (excluding keys and time features)
    exclude_cols = ['customer_unique_id', 'nameOrig', 'nameDest', 'step',
                    'order_purchase_timestamp', 'time_of_day', 'day_of_week',
                    'order_hour', 'order_dayofweek']
    numeric_cols = merged.select_dtypes(include=[np.number]).columns.tolist()
    numeric_cols = [c for c in numeric_cols if c not in exclude_cols]

    # Choose grouping column for outlier detection (e.g., PaySim 'type' or Olist state if available)
    group_by = None
    if 'type' in merged.columns:          # PaySim transaction type (CASH-IN, CASH-OUT, etc.)
        group_by = 'type'
    elif 'customer_state' in merged.columns:
        group_by = 'customer_state'

    for col in numeric_cols:
        if merged[col].isnull().any():
            merged = impute_numeric_column_per_group(merged, col, group_col=group_by)

    # Impute categorical columns
    categorical_cols = merged.select_dtypes(include=['object', 'category']).columns.tolist()
    categorical_cols = [c for c in categorical_cols if c not in exclude_cols + ['type', 'customer_state']]
    for col in categorical_cols:
        if merged[col].isnull().any():
            merged = impute_categorical_column(merged, col)

    # ---- 5.8 Missing values after imputation ----
    print("\n[8] Missing values AFTER imputation:")
    missing_after = merged.isnull().sum()
    print(missing_after[missing_after > 0] if (missing_after > 0).any() else "   No missing values left.")

    # ---- 5.9 Memory optimisation (downcasting) ----
    print("\n[9] Optimising data types (downcasting & categoricals)...")
    merged = optimise_dtypes(merged)
    print("   Memory optimisation completed.")

    print("\n" + "="*60)
    print("PoC COMPLETED SUCCESSFULLY")
    print("="*60)
    return merged

# 6. Execution (Google Colab with mounted Drive)
# ------------------------------
if __name__ == "__main__":
    # Mount Google Drive (if files are stored there)
    drive.mount('/content/drive')

    # Update these paths to match your actual file locations.
    # Example: '/content/drive/MyDrive/olist/olist_customers_dataset.csv'
    CUSTOMERS_FILE = '/content/olist_customers_dataset.csv'
    ORDERS_FILE    = '/content/olist_orders_dataset.csv'
    PAYSIM_FILE    = '/content/PS_20174392719_1491204439457_log.csv'

    # Run the PoC with 100,000 rows per sample
    final_df = run_poc(CUSTOMERS_FILE, ORDERS_FILE, PAYSIM_FILE, sample_size=100000)

    print("\nFinal merged dataset preview (first 5 rows):")
    print(final_df.head())
    print(f"\nFinal dataset memory usage: {final_df.memory_usage(deep=True).sum() / 1024**2:.2f} MB")

print("\n--- Investigating Merge Keys ---")

# Re-load samples to inspect columns
CUSTOMERS_FILE = '/content/olist_customers_dataset.csv'
PAYSIM_FILE    = '/content/PS_20174392719_1491204439457_log.csv'

# Using the random_sample_csv function to get consistent samples
customers_sample_for_inspection = random_sample_csv(CUSTOMERS_FILE, sample_size=100000)
paysim_sample_for_inspection = random_sample_csv(PAYSIM_FILE, sample_size=100000)

print("\nOlist Customers 'customer_unique_id':")
print(f"  Dtype: {customers_sample_for_inspection['customer_unique_id'].dtype}")
print(f"  Unique values: {customers_sample_for_inspection['customer_unique_id'].nunique()}")
print(f"  Sample values: {customers_sample_for_inspection['customer_unique_id'].head().tolist()}")

print("\nPaySim 'nameOrig':")
print(f"  Dtype: {paysim_sample_for_inspection['nameOrig'].dtype}")
print(f"  Unique values: {paysim_sample_for_inspection['nameOrig'].nunique()}")
print(f"  Sample values: {paysim_sample_for_inspection['nameOrig'].head().tolist()}")

# Check for common values if any
common_ids = set(customers_sample_for_inspection['customer_unique_id']).intersection(set(paysim_sample_for_inspection['nameOrig']))
print(f"\nNumber of common unique IDs (Olist customer_unique_id ∩ PaySim nameOrig): {len(common_ids)}")
if len(common_ids) > 0:
    print(f"Sample of common IDs: {list(common_ids)[:5]}")
else:
    print("No common IDs found between Olist customer_unique_id and PaySim nameOrig.")

# Synthetic ID Mapping & Feature Engineering for Credit Scoring PoC
# Extends the previous working Olist + PaySim pipeline

import pandas as pd
import numpy as np
import random
from google.colab import drive
from datetime import timedelta

# 1. Reuse existing helper functions (sampling, imputation, optimisation)
# ------------------------------------------------------------------
def random_sample_csv(file_path, sample_size=100000, chunksize=10000, random_state=42):
    random.seed(random_state)
    np.random.seed(random_state)
    with open(file_path, 'r') as f:
        total_rows = sum(1 for _ in f) - 1
    frac = sample_size / total_rows if total_rows > sample_size else 1.0
    sampled_dfs = []
    for chunk in pd.read_csv(file_path, chunksize=chunksize):
        sampled_chunk = chunk.sample(frac=frac, random_state=random_state)
        sampled_dfs.append(sampled_chunk)
        current_size = sum(len(df) for df in sampled_dfs)
        if current_size >= sample_size * 1.1:
            break
    result = pd.concat(sampled_dfs, ignore_index=True)
    if len(result) > sample_size:
        result = result.sample(n=sample_size, random_state=random_state)
    return result

def optimise_dtypes(df):
    for col in df.columns:
        col_type = df[col].dtype
        if col_type == 'int64':
            df[col] = pd.to_numeric(df[col], downcast='integer')
        elif col_type == 'float64':
            df[col] = pd.to_numeric(df[col], downcast='float')
        elif col_type == 'object':
            if df[col].nunique() / len(df) < 0.5 and df[col].nunique() < 50:
                df[col] = df[col].astype('category')
    return df

# 2. Synthetic one-to-one mapping (Olist customer ↔ PaySim nameOrig)
# ------------------------------------------------------------------
def create_synthetic_mapping(customers_df, paysim_df, random_state=42):
    """
    Creates a one-to-one mapping: each customer_unique_id gets a unique nameOrig.
    If sizes differ, the smaller set determines the number of mappings.
    Returns:
        - mapping_dict: {customer_id: assigned_nameOrig}
        - customers_mapped: customers_df with new column 'mapped_nameOrig'
    """
    np.random.seed(random_state)
    unique_customers = customers_df['customer_unique_id'].drop_duplicates().values
    unique_names = paysim_df['nameOrig'].drop_duplicates().values

    n = min(len(unique_customers), len(unique_names))
    selected_customers = np.random.choice(unique_customers, n, replace=False)
    selected_names = np.random.choice(unique_names, n, replace=False)

    mapping_dict = dict(zip(selected_customers, selected_names))

    # Apply mapping to a copy of customers (keep only mapped customers)
    customers_mapped = customers_df[customers_df['customer_unique_id'].isin(selected_customers)].copy()
    customers_mapped['mapped_nameOrig'] = customers_mapped['customer_unique_id'].map(mapping_dict)
    return mapping_dict, customers_mapped

# 3. Generate synthetic Target_Credit_Score (0-100)
# ------------------------------------------------------------------
def generate_target_credit_score(df):
    """
    Weighted logic:
    - Financial Health (PaySim): balance stability (low std of balance? we use transaction success rate)
      For simplicity: success = 1 if 'isFlaggedFraud' == 0 else 0. Also newbalanceOrig / oldbalanceOrg ratio.
    - Purchase Behaviour (Olist): order frequency (scaled to 0-1), total spend (scaled)
    - Risk indicators: high amount relative to oldbalance lowers score.
    """
    # Financial health component (0-40 points)
    # Assume 'isFlaggedFraud' exists (0 = success, 1 = fraud). If not, simulate.
    if 'isFlaggedFraud' not in df.columns:
        df['isFlaggedFraud'] = 0  # default no fraud
    success_flag = (df['isFlaggedFraud'] == 0).astype(int)
    # Balance ratio (newbalanceOrig / oldbalanceOrg) - careful with division by zero
    oldbal = df['oldbalanceOrg'].replace(0, np.nan)
    balance_ratio = df['newbalanceOrig'] / oldbal
    balance_ratio = balance_ratio.fillna(1.0).clip(0, 2)  # cap at 2 for healthy
    financial_health = (success_flag * 20) + (balance_ratio * 20).clip(0, 20)

    # Purchase behaviour component (0-40 points)
    # Frequency (count of orders per customer)
    freq = df.groupby('customer_unique_id')['customer_unique_id'].transform('count')
    freq_scaled = (freq - freq.min()) / (freq.max() - freq.min() + 1e-6)
    # Monetary: if 'payment_value' not present, simulate from amount
    if 'payment_value' not in df.columns:
        # use transaction amount as proxy
        monetary = df['amount'].fillna(df['amount'].median())
    else:
        monetary = df['payment_value']
    monetary_scaled = (monetary - monetary.min()) / (monetary.max() - monetary.min() + 1e-6)
    purchase_score = (freq_scaled * 20) + (monetary_scaled * 20)

    # Risk indicators (0-20 points, higher risk subtracts)
    # High amount relative to oldbalance
    amount_ratio = df['amount'] / (df['oldbalanceOrg'] + 1)
    high_risk = (amount_ratio > 0.5).astype(int) * 10  # lose 10 points if >50% of balance
    # Also if amount is very large (top 5%)
    high_amount = (df['amount'] > df['amount'].quantile(0.95)).astype(int) * 10
    risk_penalty = high_risk + high_amount

    raw_score = financial_health + purchase_score - risk_penalty
    # Clip to 0-100
    df['Target_Credit_Score'] = raw_score.clip(0, 100).astype(int)
    return df

# 4. RFM Metrics (Recency, Frequency, Monetary)
# ------------------------------------------------------------------
def compute_rfm_features(df, reference_date=None):
    """
    Requires: 'customer_unique_id', 'order_purchase_timestamp', and a monetary column
    (either 'payment_value' or 'amount' as proxy).
    """
    if reference_date is None:
        reference_date = df['order_purchase_timestamp'].max() + timedelta(days=1)

    # Monetary
    if 'payment_value' not in df.columns:
        df['payment_value'] = df['amount']  # use PaySim amount as proxy
    # Recency: days since last purchase
    df_rfm = df.groupby('customer_unique_id').agg({
        'order_purchase_timestamp': lambda x: (reference_date - x.max()).days,
        'order_purchase_timestamp': 'count',  # will be renamed
        'payment_value': 'sum'
    }).rename(columns={
        'order_purchase_timestamp': 'Recency_days',
        'order_purchase_timestamp': 'Frequency',
        'payment_value': 'Monetary'
    })
    # Fix duplicate column name issue
    df_rfm = df.groupby('customer_unique_id').agg(
        Recency_days=('order_purchase_timestamp', lambda x: (reference_date - x.max()).days),
        Frequency=('order_purchase_timestamp', 'count'),
        Monetary=('payment_value', 'sum')
    ).reset_index()
    # Merge back
    df = df.merge(df_rfm, on='customer_unique_id', how='left')
    return df

# 5. Financial ratios from PaySim
# ------------------------------------------------------------------
def compute_financial_ratios(df):
    """Add amount_to_balance_ratio and is_high_value_transaction indicator."""
    df['amount_to_balance_ratio'] = df['amount'] / (df['oldbalanceOrg'] + 1)
    # High value if amount > 75th percentile of global amount
    high_threshold = df['amount'].quantile(0.75)
    df['is_high_value_transaction'] = (df['amount'] > high_threshold).astype(int)
    return df

# 6. NLP placeholder (review_comment_message)
# ------------------------------------------------------------------
def add_nlp_placeholder(df):
    """
    Adds a column 'review_comment_message' with placeholder text.
    In real scenario, you would merge with olist_order_reviews dataset.
    """
    sample_reviews = [
        "Great product, fast delivery!",
        "Not as described, disappointed.",
        "Excellent customer service.",
        "Delivery took longer than expected.",
        "Good value for money.",
        "Would buy again.",
        "Packaging was damaged.",
        "Very satisfied."
    ]
    df['review_comment_message'] = np.random.choice(sample_reviews, size=len(df))
    return df

# 7. Main pipeline with synthetic mapping
# ------------------------------------------------------------------
def run_credit_scoring_poc(customers_path, orders_path, paysim_path, sample_size=100000):
    print("="*70)
    print("CREDIT SCORING PoC WITH SYNTHETIC MAPPING")
    print("="*70)

    # Load samples
    print("\n[1] Loading samples...")
    customers_sample = random_sample_csv(customers_path, sample_size=sample_size)
    orders_sample = random_sample_csv(orders_path, sample_size=sample_size)
    paysim_sample = random_sample_csv(paysim_path, sample_size=sample_size)

    print(f"Customers: {customers_sample.shape}, Orders: {orders_sample.shape}, PaySim: {paysim_sample.shape}")

    # Merge Olist customers + orders
    print("\n[2] Merging Olist customers & orders on 'customer_id'...")
    olist_merged = pd.merge(customers_sample, orders_sample, on='customer_id', how='inner')
    print(f"Shape after Olist internal merge: {olist_merged.shape}")

    if olist_merged.empty:
        print("No matching customers-orders. Exiting.")
        return pd.DataFrame()

    # Keep necessary columns
    olist_ready = olist_merged[['customer_unique_id', 'order_purchase_timestamp']].drop_duplicates()

    # Create synthetic mapping
    print("\n[3] Creating synthetic one-to-one mapping...")
    mapping_dict, olist_mapped = create_synthetic_mapping(olist_ready, paysim_sample)
    print(f"Mapped {len(mapping_dict)} customers to unique PaySim nameOrig.")

    # Merge using synthetic mapping
    print("\n[4] Merging Olist (via mapped_nameOrig) with PaySim (nameOrig)...")
    merged = pd.merge(
        olist_mapped,
        paysim_sample,
        left_on='mapped_nameOrig',
        right_on='nameOrig',
        how='inner'
    )
    print(f"Final merged shape: {merged.shape}")

    if merged.empty:
        print("Merge still empty – something went wrong. Check mapping.")
        return pd.DataFrame()

    # Time features
    print("\n[5] Time-series transformations...")
    merged['order_purchase_timestamp'] = pd.to_datetime(merged['order_purchase_timestamp'])
    merged['order_hour'] = merged['order_purchase_timestamp'].dt.hour
    merged['order_dayofweek'] = merged['order_purchase_timestamp'].dt.dayofweek

    # RFM metrics
    print("\n[6] Computing RFM features...")
    merged = compute_rfm_features(merged)

    # Financial ratios
    print("\n[7] Computing financial ratios...")
    merged = compute_financial_ratios(merged)

    # Generate target credit score
    print("\n[8] Generating synthetic Target_Credit_Score...")
    merged = generate_target_credit_score(merged)

    # NLP placeholder
    print("\n[9] Adding NLP placeholder (review_comment_message)...")
    merged = add_nlp_placeholder(merged)

    # Memory optimisation
    print("\n[10] Optimising data types...")
    merged = optimise_dtypes(merged)

    # Summary
    print("\n" + "="*70)
    print("FINAL DATASET READY")
    print("="*70)
    print(f"Shape: {merged.shape}")
    print(f"Columns: {list(merged.columns)}")
    print("\nTarget_Credit_Score distribution:")
    print(merged['Target_Credit_Score'].describe(percentiles=[.1, .25, .5, .75, .9]))
    print("\nSample of new features:")
    sample_cols = ['customer_unique_id', 'Recency_days', 'Frequency', 'Monetary',
                   'amount_to_balance_ratio', 'is_high_value_transaction',
                   'Target_Credit_Score', 'review_comment_message']
    print(merged[sample_cols].head())

    return merged

# ------------------------------------------------------------------
# 8. Execution (Google Colab)
# ------------------------------------------------------------------
if __name__ == "__main__":
    drive.mount('/content/drive')

    # Update these paths to your actual files
    CUSTOMERS_FILE = '/content/olist_customers_dataset.csv'
    ORDERS_FILE    = '/content/olist_orders_dataset.csv'
    PAYSIM_FILE    = '/content/PS_20174392719_1491204439457_log.csv'

    df_final = run_credit_scoring_poc(CUSTOMERS_FILE, ORDERS_FILE, PAYSIM_FILE, sample_size=100000)

    # Final check
    print("\nMemory usage of final dataframe:")
    print(f"{df_final.memory_usage(deep=True).sum() / 1024**2:.2f} MB")

# Deep Learning Model for Credit Score Prediction (Regression)
# Requires: df_final already loaded and preprocessed

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, callbacks

# 1. Define feature columns and target
# ------------------------------
# Adjust feature list based on your actual df_final columns
# Exclude non-predictive columns like IDs, text, and the target itself
exclude_cols = ['customer_unique_id', 'mapped_nameOrig', 'nameOrig', 'nameDest',
                'order_purchase_timestamp', 'review_comment_message', 'Target_Credit_Score',
                'time_of_day', 'day_of_week']  # categorical/time features might need encoding; we drop them for simplicity

feature_cols = [col for col in df_final.columns if col not in exclude_cols]

print("Features used:")
print(feature_cols)
print(f"Number of features: {len(feature_cols)}")

X = df_final[feature_cols].copy()
# One-hot encode categorical features like 'type'
X = pd.get_dummies(X, columns=['type'], drop_first=True)
y = df_final['Target_Credit_Score'].copy()

# 2. Train-test split (80/20)
# ------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, shuffle=True
)
print(f"Train size: {X_train.shape}, Test size: {X_test.shape}")

# 3. Scaling (StandardScaler)
# ------------------------------
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 4. Build DNN model
# ------------------------------
model = keras.Sequential([
    layers.Input(shape=(X_train_scaled.shape[1],)),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.2),
    layers.Dense(32, activation='relu'),           # third hidden layer (optional)
    layers.Dropout(0.1),
    layers.Dense(1)                                 # regression output
])

model.compile(optimizer='adam', loss='mse', metrics=['mae'])
model.summary()

# 5. Early stopping callback
# ------------------------------
early_stop = callbacks.EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True,
    verbose=1
)

# 6. Train the model
# ------------------------------
history = model.fit(
    X_train_scaled, y_train,
    validation_split=0.2,          # 20% of train for validation
    epochs=50,
    batch_size=32,
    callbacks=[early_stop],
    verbose=1
)

# 8. Evaluate on test set
# ------------------------------
y_pred = model.predict(X_test_scaled).flatten()

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("\n" + "="*50)
print("TEST SET EVALUATION")
print("="*50)
print(f"Mean Squared Error (MSE):  {mse:.4f}")
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"R-squared (R²):            {r2:.4f}")
print("="*50)

# Optional: scatter plot of true vs predicted
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred, alpha=0.5, edgecolors='k')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
plt.xlabel('True Credit Score')
plt.ylabel('Predicted Credit Score')
plt.title('True vs Predicted Credit Score (Test Set)')
plt.grid(True)
plt.show()

# NLP Sentiment Integration for Credit Scoring (Olist Reviews)
# Requires: df_final already exists ('review_comment_message' column)

# Install required libraries (if not already present)
!pip install textblob
!python -m textblob.download_corpora  # download necessary NLTK data

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from textblob import TextBlob
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, r2_score
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, callbacks

# ------------------------------
# 1. Sentiment Extraction from review_comment_message
# ------------------------------
def get_sentiment_polarity(text):
    """Return polarity score (-1 to 1). If text is missing or empty, return 0."""
    if pd.isna(text) or str(text).strip() == "":
        return 0.0
    try:
        return TextBlob(str(text)).sentiment.polarity
    except:
        return 0.0

print("Extracting sentiment polarity from review comments...")
df_final['sentiment_polarity'] = df_final['review_comment_message'].apply(get_sentiment_polarity)

# 2. Visualise sentiment distribution & correlation
# ------------------------------
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Histogram of sentiment scores
axes[0].hist(df_final['sentiment_polarity'], bins=30, edgecolor='black', alpha=0.7)
axes[0].set_title('Distribution of Sentiment Polarity Scores')
axes[0].set_xlabel('Polarity (-1 = negative, 1 = positive)')
axes[0].set_ylabel('Frequency')
axes[0].axvline(x=0, color='red', linestyle='--', label='Neutral')
axes[0].legend()

# Correlation with Target_Credit_Score (scatter plot + regression line)
sns.regplot(x='sentiment_polarity', y='Target_Credit_Score', data=df_final,
            scatter_kws={'alpha':0.3}, line_kws={'color':'red'}, ax=axes[1])
axes[1].set_title('Sentiment vs Target Credit Score')
axes[1].set_xlabel('Sentiment Polarity')
axes[1].set_ylabel('Target Credit Score')

plt.tight_layout()
plt.show()

# Compute correlation coefficient
corr = df_final['sentiment_polarity'].corr(df_final['Target_Credit_Score'])
print(f"Correlation between sentiment polarity and credit score: {corr:.4f}")

# 3. Prepare feature set (includes sentiment)
# ------------------------------
# Same feature columns as before, plus sentiment_polarity
exclude_cols = ['customer_unique_id', 'mapped_nameOrig', 'nameOrig', 'nameDest',
                'order_purchase_timestamp', 'review_comment_message', 'Target_Credit_Score',
                'time_of_day', 'day_of_week']
# Keep existing numerical features + sentiment
feature_cols = [col for col in df_final.columns if col not in exclude_cols]
print(f"Features now include: {feature_cols}")

X = df_final[feature_cols].copy()
y = df_final['Target_Credit_Score'].copy()

# Train-test split (same seed for consistency)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, shuffle=True
)

# Standard scaling (fit on train, transform both)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 4. Define DNN architecture (same as before, input dimension increases)
# ------------------------------
model = keras.Sequential([
    layers.Input(shape=(X_train_scaled.shape[1],)),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.2),
    layers.Dense(32, activation='relu'),
    layers.Dropout(0.1),
    layers.Dense(1)
])

model.compile(optimizer='adam', loss='mse', metrics=['mae'])
print("\nModel with Sentiment Feature:")
model.summary()

# Early stopping
early_stop = callbacks.EarlyStopping(
    monitor='val_loss', patience=10, restore_best_weights=True, verbose=1
)



# 5. Train the model
# ------------------------------
history = model.fit(
    X_train_scaled, y_train,
    validation_split=0.2,
    epochs=50,
    batch_size=32,
    callbacks=[early_stop],
    verbose=1
)

# 6. Evaluate on test set
# ------------------------------
y_pred = model.predict(X_test_scaled).flatten()
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("\n" + "="*50)
print("TEST SET EVALUATION (WITH SENTIMENT)")
print("="*50)
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"R-squared (R²):            {r2:.4f}")
print("="*50)

# 7. Risk Flag Logic: Very negative sentiment lowers predicted score
# ------------------------------
def apply_sentiment_risk_penalty(predictions, sentiments, threshold=-0.5, penalty=5):
    """
    If sentiment < threshold, reduce prediction by penalty points.
    Ensures final score stays within [0, 100].
    """
    adjusted = predictions.copy()
    mask = sentiments < threshold
    adjusted[mask] = adjusted[mask] - penalty
    adjusted = np.clip(adjusted, 0, 100)
    return adjusted

# Get sentiment for test set
test_sentiments = X_test['sentiment_polarity'].values

# Apply penalty to model predictions
y_pred_adjusted = apply_sentiment_risk_penalty(y_pred, test_sentiments)

# Evaluate adjusted predictions
mae_adj = mean_absolute_error(y_test, y_pred_adjusted)
r2_adj = r2_score(y_test, y_pred_adjusted)

print("\n" + "="*50)
print("AFTER SENTIMENT RISK PENALTY (negative sentiment -> -5 points)")
print("="*50)
print(f"Original MAE:  {mae:.4f}  |  Adjusted MAE:  {mae_adj:.4f}")
print(f"Original R²:   {r2:.4f}   |  Adjusted R²:   {r2_adj:.4f}")
print("="*50)

# 8. Compare with previous numerical‑only model (assume you saved metrics)
# ------------------------------
# If you have previous metrics from the numerical-only model stored, load them.
# For demonstration, we simulate typical values (you should replace with actual)
# In a real scenario, you would have saved previous_mae, previous_r2 variables.

# Example placeholder (replace with your actual numbers)
previous_mae = 3.2   # example
previous_r2 = 0.94   # example

print("\n" + "="*50)
print("PERFORMANCE COMPARISON")
print("="*50)
print(f"Numerical‑only model | MAE: {previous_mae:.4f}, R²: {previous_r2:.4f}")
print(f"With sentiment       | MAE: {mae:.4f}, R²: {r2:.4f}")
print(f"After risk penalty   | MAE: {mae_adj:.4f}, R²: {r2_adj:.4f}")
print("="*50)

# Optional: plot loss curves
plt.figure(figsize=(10, 5))
plt.plot(history.history['loss'], label='Training Loss (MSE)')
plt.plot(history.history['val_loss'], label='Validation Loss (MSE)')
plt.title('Model Training with Sentiment Feature')
plt.xlabel('Epochs')
plt.ylabel('MSE')
plt.legend()
plt.grid(True)
plt.show()

# Model Explainability using SHAP for Credit Scoring PoC
# Run this after training the DNN model with sentiment feature

# 1. Install SHAP (if not already installed)
!pip install shap

import shap
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras

# Assume the following variables exist from previous training:
# - model : trained Keras model
# - X_train_scaled, X_test_scaled : scaled numpy arrays
# - feature_names : list of feature column names (same order as training)
# - scaler : fitted StandardScaler (if needed for inverse transform, but SHAP works on scaled inputs)

# ------------------------------
# 2. Prepare a background dataset for DeepExplainer
# ------------------------------
# DeepExplainer requires a representative background sample (e.g., 100 random points from training)
background = X_train_scaled[np.random.choice(X_train_scaled.shape[0], 100, replace=False)]

# 3. Initialize SHAP DeepExplainer
# ------------------------------
# Note: SHAP's DeepExplainer works with TensorFlow 2.x but may require a custom session.
# If you encounter errors, switch to KernelExplainer (slower but more robust).
try:
    explainer = shap.DeepExplainer(model, background)
    print("Using DeepExplainer (optimized for deep models)")
except Exception as e:
    print(f"DeepExplainer failed: {e}\nFalling back to KernelExplainer (slower but works).")
    # KernelExplainer requires a prediction function
    def predict_fn(x):
        return model.predict(x).flatten()
    # Use a smaller background for KernelExplainer
    background_kernel = X_train_scaled[np.random.choice(X_train_scaled.shape[0], 50, replace=False)]
    explainer = shap.KernelExplainer(predict_fn, background_kernel)

# 4. Global Interpretability - Summary Plot
# ------------------------------
# Define feature_names from the X DataFrame (after one-hot encoding)
feature_names = X.columns.tolist()

# Compute SHAP values for a random subset of test set (e.g., 200 samples) to keep runtime reasonable
test_subset = X_test_scaled[np.random.choice(X_test_scaled.shape[0], 200, replace=False)]
shap_values = explainer.shap_values(test_subset)

# For DeepExplainer, shap_values may be a list (if model has multiple outputs) or a single array.
# Our model has a single output, so we take the first element if it's a list.
if isinstance(shap_values, list):
    shap_values = shap_values[0]

# Summary plot (bee swarm)
plt.figure(figsize=(12, 8))
shap.summary_plot(shap_values, test_subset, feature_names=feature_names, show=False)
plt.title("SHAP Feature Importance Summary", fontsize=14)
plt.tight_layout()
plt.show()

# Bar plot of mean |SHAP| (feature importance)
plt.figure(figsize=(10, 6))
shap.summary_plot(shap_values, test_subset, feature_names=feature_names, plot_type="bar", show=False)
plt.title("Mean Absolute SHAP Values (Feature Importance)", fontsize=14)
plt.tight_layout()
plt.show()

# ------------------------------
# 5. Local Interpretability - Function for Individual Customer
# ------------------------------
def explain_customer_decision(customer_index, X_scaled, shap_values_all=None, feature_names=None, model=None, scaler=None):
    """
    Generate a waterfall plot and a human-readable explanation for a single customer.

    Parameters:
    - customer_index: row index in X_test_scaled (or any scaled array)
    - X_scaled: the full scaled test array (numpy)
    - shap_values_all: precomputed SHAP values for the entire test set (optional, will compute if None)
    - feature_names: list of feature names
    - model: trained Keras model (needed if computing SHAP on the fly)
    - scaler: fitted StandardScaler (for inverse transforming values to original scale)

    Returns:
    - A waterfall plot displayed inline
    - A printed plain‑English summary
    """
    if shap_values_all is None:
        # Compute SHAP values for this single sample (expensive, but works)
        sample = X_scaled[customer_index:customer_index+1]
        shap_val = explainer.shap_values(sample)
        if isinstance(shap_val, list):
            shap_val = shap_val[0]
        shap_val = np.array(shap_val).flatten() # Ensure it's 1D
    else:
        # shap_values_all is expected to be (num_samples, num_features, 1) or (num_samples, num_features)
        # Extract the specific customer's SHAP values
        shap_val = shap_values_all[customer_index]
        shap_val = np.array(shap_val).flatten() # Ensure it's 1D

    # Process base_values to ensure it's a scalar or numpy array, not a TF tensor
    base_value = explainer.expected_value
    if isinstance(base_value, tf.Tensor):
        base_value = base_value.numpy()
    if isinstance(base_value, list):
        base_value = base_value[0]

    # Waterfall plot
    plt.figure(figsize=(12, 6))
    shap.waterfall_plot(
        shap.Explanation(
            values=shap_val, # shap_val is now guaranteed to be 1D
            base_values=base_value,
            data=X_scaled[customer_index],
            feature_names=feature_names
        ),
        show=False
    )
    plt.title(f"SHAP Waterfall Plot for Customer {customer_index}", fontsize=14)
    plt.tight_layout()
    plt.show()

    # Human-readable explanation
    # Get original (unscaled) feature values if scaler provided
    if scaler:
        original_values = scaler.inverse_transform(X_scaled[customer_index:customer_index+1])[0]
    else:
        original_values = X_scaled[customer_index]

    # Compute contribution direction
    contributions = []
    for i, name in enumerate(feature_names):
        shap_contrib = shap_val[i] # shap_val is already 1D
        if abs(shap_contrib) > 0.05:  # only show non‑trivial contributions
            direction = "increased" if shap_contrib > 0 else "decreased"
            contributions.append(f"{name}: {shap_contrib:+.2f} points")

    # Sort by absolute magnitude
    contributions_sorted = sorted(contributions, key=lambda x: abs(float(x.split(':')[1].split()[0])), reverse=True)
    # Build message
    pred_score = model.predict(X_scaled[customer_index:customer_index+1])[0][0]
    top_positive = [c for c in contributions_sorted if '+' in c][:2]
    top_negative = [c for c in contributions_sorted if '-' in c][:2]

    explanation = f"Customer {customer_index} received a predicted credit score of {pred_score:.1f}.\n"
    if top_positive:
        explanation += f"  Positive contributors: {', '.join(top_positive)}.\n"
    if top_negative:
        explanation += f"  Negative contributors: {', '.join(top_negative)}.\n"
    if not contributions_sorted:
        explanation += "  All features had negligible impact (near baseline)."

    print("\n" + "="*70)
    print("🔍 LOCAL EXPLANATION (Human‑Readable)")
    print("="*70)
    print(explanation)
    print("="*70)

    return shap_val

# 6. Compute SHAP values for entire test set (optional, can be time‑consuming)
# ------------------------------
# For better performance, compute once and reuse in the function.
# Since DeepExplainer can be slow on large test sets, we compute for a subset.
# Here we compute for the first 100 test samples as an example.
print("Computing SHAP values for 100 test samples (this may take a minute)...")
test_subset_for_local = X_test_scaled[:100]
shap_values_test = explainer.shap_values(test_subset_for_local)
if isinstance(shap_values_test, list):
    shap_values_test = shap_values_test[0]

# 7. Example: Explain a specific customer (e.g., index 5)
# ------------------------------
customer_idx = 5  # change to any index in test set (0-99)
explain_customer_decision(
    customer_index=customer_idx,
    X_scaled=test_subset_for_local,
    shap_values_all=shap_values_test,
    feature_names=feature_names,
    model=model,
    scaler=scaler  # optional: provide scaler to show original values
)

# 8. Business Insight: How model prioritises financial vs behavioural factors
# ------------------------------
# Extract mean absolute SHAP per feature category
# Assume feature names contain keywords like 'amount', 'balance' for financial,
# and 'Frequency', 'Recency', 'Monetary', 'sentiment' for behaviour.
financial_keywords = ['amount', 'balance', 'ratio', 'oldbalance', 'newbalance']
behaviour_keywords = ['Frequency', 'Recency', 'Monetary', 'sentiment', 'order_hour', 'dayofweek']

financial_shap = []
behaviour_shap = []
for i, name in enumerate(feature_names):
    mean_abs = np.abs(shap_values_test[:, i]).mean()
    if any(kw in name.lower() for kw in financial_keywords):
        financial_shap.append(mean_abs)
    elif any(kw in name.lower() for kw in behaviour_keywords):
        behaviour_shap.append(mean_abs)

print("\n" + "="*70)
print("🏦 BUSINESS LOGIC TRANSLATION: Feature Prioritisation")
print("="*70)
print(f"Average importance (mean |SHAP|) for Financial features: {np.mean(financial_shap):.4f}")
print(f"Average importance for Behavioural features:         {np.mean(behaviour_shap):.4f}")
if np.mean(financial_shap) > np.mean(behaviour_shap):
    print("→ The model relies more on FINANCIAL health (balance, transaction amounts).")
else:
    print("→ The model relies more on PURCHASE BEHAVIOUR (RFM, sentiment).")
print("="*70)

# Save the trained model, scaler, feature names, and safe average
import joblib
import tensorflow as tf

# 1. Save the Keras model
model.save('credit_model.h5')  # or 'credit_model.keras'
print("✅ Saved credit_model.h5")

# 2. Save the scaler
joblib.dump(scaler, 'scaler.joblib')
print("✅ Saved scaler.joblib")

# 3. Save feature names (list of column names used for training)
joblib.dump(feature_names, 'feature_names.joblib')
print("✅ Saved feature_names.joblib")

# 4. If 'safe_avg' exists, save it; otherwise compute it from training data
try:
    joblib.dump(safe_avg, 'average_safe_customer.joblib')
    print("✅ Saved average_safe_customer.joblib")
except NameError:
    print("⚠️ safe_avg not found. Computing from y_train and X_train...")
    # Compute safe average (credit score > 70)
    safe_mask = y_train > 70
    X_train_safe = X_train.loc[safe_mask, feature_names]  # use original X_train (not scaled)
    safe_avg = X_train_safe.mean().to_dict()
    joblib.dump(safe_avg, 'average_safe_customer.joblib')
    print("✅ Saved average_safe_customer.joblib")

from google.colab import files
import os

files_to_download = [
    'credit_model.h5',
    'scaler.joblib',
    'feature_names.joblib',
    'average_safe_customer.joblib'
]

for f in files_to_download:
    if os.path.exists(f):
        print(f"Downloading {f}...")
        files.download(f)
    else:
        print(f"Warning: {f} not found. Did you run the save cell?")